"""2026-10-08 渠道装填刷新 + 三份体例适配版生成"""
import io
import os
import re
import shutil
import sys

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
ROOT = r'D:\xiyouji\docs\S4-学术投稿'
SRC = os.path.join(ROOT, '01-论文')
BSRC = os.path.join(ROOT, '05-投稿', '装饰投稿')
fails = []

def cp(src, dst_dir, name):
    s = os.path.join(ROOT, src) if not src.startswith('05') else os.path.join(ROOT, src)
    d = os.path.join(ROOT, '05-投稿', dst_dir, name)
    if not os.path.exists(s):
        fails.append(f'cp 缺源 {src}')
        return
    shutil.copyfile(s, d)
    print('cp ->', dst_dir + '/' + name)

# ============ 1. 副本刷新（装填清单全表） ============
JOBS = [
    ('01-论文/明清小说方向-投稿版.md', 'CSSCI投稿', '明清小说方向-投稿版.md'),
    ('01-论文/明清小说方向-匿名稿.md', 'CSSCI投稿', '明清小说方向-匿名稿.md'),
    ('05-投稿/装饰投稿/设计方向-装饰投稿版.md', 'CSSCI投稿', '设计方向-装饰投稿版.md'),
    ('05-投稿/装饰投稿/设计方向-匿名稿.md', 'CSSCI投稿', '设计方向-匿名稿.md'),
    ('01-论文/可验证性方向-投稿版.md', 'CSSCI投稿', '可验证性方向-投稿版.md'),
    ('01-论文/可验证性方向-匿名稿.md', 'CSSCI投稿', '可验证性方向-匿名稿.md'),
    ('01-论文/明清小说方向-投稿版.md', '明清小说研究投稿', '明清小说方向-投稿版.md'),
    ('01-论文/明清小说方向-匿名稿.md', '明清小说研究投稿', '明清小说方向-匿名稿.md'),
    ('01-论文/可验证性方向-投稿版.md', '数字人文研究投稿', '可验证性方向-投稿版.md'),
    ('01-论文/可验证性方向-匿名稿.md', '数字人文研究投稿', '可验证性方向-匿名稿.md'),
    ('01-论文/明清小说方向-投稿版.md', '数字人文研究投稿', '明清小说方向-投稿版.md'),
    ('01-论文/明清小说方向-匿名稿.md', '数字人文研究投稿', '明清小说方向-匿名稿.md'),
    ('01-论文/可验证性方向-投稿版.md', '科技与出版投稿', '可验证性方向-投稿版.md'),
    ('01-论文/可验证性方向-英文short-paper.md', 'SSCI投稿', '可验证性方向-英文short-paper.md'),
    ('01-论文/心学方向-投稿版.md', '中文核心期刊要目总览投稿', '心学方向-投稿版.md'),
    ('01-论文/心学方向-匿名稿.md', '中文核心期刊要目总览投稿', '心学方向-匿名稿.md'),
    ('05-投稿/装饰投稿/设计方向-装饰投稿版.md', '南京艺术学院学报（美术与设计）投稿', '设计方向-装饰投稿版.md'),
    ('05-投稿/装饰投稿/设计方向-匿名稿.md', '南京艺术学院学报（美术与设计）投稿', '设计方向-匿名稿.md'),
    ('05-投稿/装饰投稿/设计方向-装饰投稿版.md', '艺术百家投稿', '设计方向-装饰投稿版.md'),
    ('05-投稿/装饰投稿/设计方向-匿名稿.md', '艺术百家投稿', '设计方向-匿名稿.md'),
    ('05-投稿/装饰投稿/设计方向-装饰投稿版.md', '新美术投稿', '设计方向-装饰投稿版.md'),
    ('05-投稿/装饰投稿/设计方向-匿名稿.md', '新美术投稿', '设计方向-匿名稿.md'),
    ('05-投稿/装饰投稿/设计方向-装饰投稿版.md', '设计投稿', '设计方向-装饰投稿版.md'),
    ('05-投稿/装饰投稿/设计方向-装饰投稿版.md', '艺术设计研究投稿', '设计方向-装饰投稿版.md'),
    ('01-论文/明清小说方向-投稿版.md', '文艺研究投稿', '明清小说方向-投稿版.md'),
]
for src, d, name in JOBS:
    cp(src, d, name)

# ============ 2. 数字人文研究版·可验证性方向 ============
EN_ABS = (
    '**Abstract**: After generative AI entered digital humanities production workflows, hallucinated citations became a measurable integrity risk. '
    'Existing countermeasures are external: manual checking does not scale, AI-text detectors do not target citation entities, and platform bans take effect only after publication. '
    'This article proposes and evaluates a three-layer verifiability infrastructure embedded in the production pipeline of a Journey to the West digital humanities project (615 documents and a 100-chapter electronic base text): '
    'an anchor layer that locates every claim at "chapter N, line X"; a verification layer that requires every primary-source quotation to match the public base text as an exact whitespace-normalized substring, failing on any mismatch; '
    'and a gate layer that turns verification into a mandatory path for every delivery. In the batch reported here, all 439 quotation lines matched across 892 files in sub-second time. '
    'Two cases expose the system\u2019s boundary and value: how a well-formatted phantom reference survived for seven weeks across two manuscripts before external authoritative anchoring caught it and was purged across the chain; '
    'and how a "fourteen gates all green while 224 pages of inline styles were wiped" incident revealed the non-closure of gates themselves. '
    'The core claim: in AI-involved production, what deserves building is infrastructure, not discipline.'
)
CNY_MAP = {
    '> 投稿目标：《数字人文》（清华大学·中华书局）「基础设施」栏目首投 → ADHO DH conference short paper':
    '> 投稿目标：《数字人文研究》（中国人民大学·季刊·CN 10-1716/C）——在线系统投稿（dhr.ruc.edu.cn 作者中心）\n> 适配版说明：2026-10-08 依该刊官方投稿指南（字数 8000-15000·中英文摘要必需要素·参考文献 GB/T 7714—2015·不收费·署名刊用后不可更改）生成；体例差异清单见同夹 [投稿要求-2026-10-08.md](投稿要求-2026-10-08.md)。单篇刊出实样（简锦松等 6(2)）供版式参照。',
}
REFS = '''
## 参考文献

[1] Walters W H, Wilder E I. Fabrication and errors in the bibliographic citations generated by ChatGPT[J]. Scientific Reports, 2023, 13: 14045.
[2] Topaz M, Roguin N, et al. Fabricated citations: an audit across 2.5 million biomedical papers[J]. The Lancet, 2026, 407(10541): 1779-1781.
[3] Zhao Z, Wang Y, Stuart T, et al. LLM hallucinations in the wild: large-scale evidence from non-existent citations[EB/OL]. (2026-05-08). https://arxiv.org/abs/2605.07723.
[4] Naddaf M, Quill E. Hallucinated citations are polluting the scientific literature[J]. Nature, 2026, 652: 26-29.
[5] Jergas H, Baethge C. Quotation accuracy in medical journal articles: a systematic review and meta-analysis[J]. PeerJ, 2015, 3: e1364.
[6] Resnik D B, Hosseini M. Hallucinated citations produced by generative artificial intelligence may constitute research misconduct when citations function as claims[J]. Accountability in Research, 2026, 33(7).
[7] Russinovich M, Siva Kumar R S, Salem A. Phantom references: hallucinated citations that survive peer review at top-tier conferences[EB/OL]. (2026). https://arxiv.org/abs/2607.00738.
[8] Franzone R. A citation verification framework for LLMs in sensitive domains[EB/OL]. (2026-04-10). The AI Journal.
[9] Shi K, Sun W, Zhang Z, et al. CiteAudit: you cited it, but did you read it? A benchmark for verifying scientific references in the LLM era[EB/OL]. (2026-02-26). https://arxiv.org/abs/2602.23452.
[10] Xu Z, Qiu Y, Sun L, et al. GhostCite: a large-scale analysis of citation validity in the age of large language models[EB/OL]. (2026-02-06). https://arxiv.org/abs/2602.06718.
[11] Sakai Y, Kamigaito H, Watanabe T. HalluCiteChecker: a lightweight toolkit for hallucinated citation detection and verification in the era of AI scientists[EB/OL]. (2026-04-29). https://arxiv.org/abs/2604.26835.
[12] Neralla H, Lee J, Romero A H, et al. Hallucination detector: a hybrid LLM and Semantic Scholar tool calling——AtomGPT.org[EB/OL]. (2026-07-07). https://arxiv.org/abs/2607.09774.
[13] Badalova F, Mayr P. Detecting hallucinated and suspicious citations: what current tools can and cannot do[EB/OL]. (2026-07-17). https://arxiv.org/abs/2607.22693.
[14] linkml-reference-validator[CP/OL]. https://pypi.org/project/linkml-reference-validator/.
'''

def make_dhr():
    src = os.path.join(SRC, '可验证性方向-投稿版.md')
    t = open(src, encoding='utf-8', newline='').read()
    for old, new in CNY_MAP.items():
        if t.count(old) != 1:
            fails.append(f'DHR 头注锚点缺失: {old[:30]}')
            return
        t = t.replace(old, new)
    # 英文摘要插在关键词行后
    kw_anchor = '**关键词**：数字人文；生成式人工智能；幻觉引文；引文核验；可验证性基础设施；《西游记》'
    if t.count(kw_anchor) != 1:
        fails.append('DHR 关键词锚点缺失')
        return
    t = t.replace(kw_anchor, kw_anchor + '\n\n' + EN_ABS + '\n\n**Keywords**: digital humanities; generative AI; hallucinated citations; citation verification; verifiability infrastructure; *Journey to the West*')
    # 中图分类号/作者简介占位（关键词后）
    t = t.replace('**Keywords**: digital humanities; generative AI; hallucinated citations; citation verification; verifiability infrastructure; *Journey to the West*',
                  '**Keywords**: digital humanities; generative AI; hallucinated citations; citation verification; verifiability infrastructure; *Journey to the West*\n\n**中图分类号**：（待定，候选 G256/G258）　**文献标识码**：A\n\n**作者简介**：（投稿时填写：姓名，单位，职称；通讯邮箱。）')
    # 文末参考文献：插在「## 五、讨论」之前的结构不合适——插在 AI 声明段之后、仓库内部节之前
    anchor = '本文的生产过程使用生成式 AI 工具'
    i = t.find(anchor)
    if i < 0:
        fails.append('DHR AI 声明锚点缺失')
        return
    j = t.find('\n## ', i)  # AI 声明所在节的结尾（下一个节标题）——取该节末尾
    # 更稳：插在「---\n\n## 关联文档」或文件尾的仓库节之前
    k = t.find('## 关联文档')
    if k < 0:
        k = len(t)
    # 回退到该节前的 ---
    ins = t.rfind('---', i, k)
    t = t[:ins] + REFS + '\n\n---\n\n' + t[ins:]
    # 剔除仓库内部节（关联文档）
    k2 = t.find('## 关联文档')
    if k2 >= 0:
        t = t[:k2].rstrip() + '\n'
    out = os.path.join(ROOT, '05-投稿', '数字人文研究投稿', '可验证性方向-数字人文研究适配版.md')
    open(out, 'w', encoding='utf-8', newline='').write(t)
    print('written', os.path.basename(out), len(t), 'chars')

make_dhr()

# ============ 3. 南艺版·设计方向（匿名形态） ============
B_EN_ABS = (
    '**Abstract**: Turning classical Chinese literature into data visualization all too often yields a generic dashboard: western templates, blue-violet palettes, and motion without cultural semantics. '
    'Based on 86 interactive visualizations from a *Journey to the West* digital humanities project, this article proposes a replicable "New Chinese Style · Digital Literati Gathering" design system. '
    'Three hues extracted from the motif\u2014rice-paper ground, ink text, and cinnabar accent\u2014are encoded as design tokens and distributed through a three-layer architecture to 334 pages; '
    'motion is constrained to three duration tiers and three easing curves; accessibility is enforced by CSS/JS dual guards; and a single-source, multi-form pipeline replicates the system at the 86-page scale. '
    'The practice shows that indigenous aesthetics can be written into tokens, specifications, and gates, becoming a transferable design methodology.'
)
def make_nanyi():
    src = os.path.join(BSRC, '设计方向-匿名稿.md')
    t = open(src, encoding='utf-8', newline='').read()
    # 头注追加适配说明
    lines = t.split('\n')
    ins_i = 0
    for i, ln in enumerate(lines[:8]):
        if ln.startswith('>'):
            ins_i = i + 1
    add = '> 适配版说明：2026-10-08 依《南京艺术学院学报（美术与设计版）》官网投稿须知（2026-10-08 直采）生成——双盲匿名（本稿即匿名形态）；摘要≤300 字✓；关键词 3-6✓；**篇名/姓名/单位/摘要/关键词五项英译**（英译摘要见下·姓名单位英译署名版补）；体例改**脚注①②③＋文末参考文献 [1][2] GB 7714 双轨**（现尾注制①-⑲+[1]-[5] 的转换在 docx 生成器变体执行）；投稿=邮箱 83498094@163.com 附件＋纸质邮寄双轨·**截稿单月 1 日**。差异清单见同夹 [投稿要求-2026-10-08.md](投稿要求-2026-10-08.md)。'
    lines.insert(ins_i, add)
    t = '\n'.join(lines)
    # 英文摘要：插在中文摘要段之后（首个 **关键词** 行后若无，找摘要段尾）
    m = re.search(r'(把古典文学做成数据可视化[^\n]*\n)', t)
    if not m:
        fails.append('南艺版 中文摘要锚点缺失')
        return
    t = t.replace(m.group(1), m.group(1) + '\n' + B_EN_ABS + '\n', 1)
    out = os.path.join(ROOT, '05-投稿', '南京艺术学院学报（美术与设计）投稿', '设计方向-南艺适配版（匿名）.md')
    open(out, 'w', encoding='utf-8', newline='').write(t)
    print('written', os.path.basename(out), len(t), 'chars')

make_nanyi()

# ============ 4. 艺术百家版·设计方向（匿名形态） ============
def make_ysbj():
    src = os.path.join(BSRC, '设计方向-匿名稿.md')
    t = open(src, encoding='utf-8', newline='').read()
    lines = t.split('\n')
    ins_i = 0
    for i, ln in enumerate(lines[:8]):
        if ln.startswith('>'):
            ins_i = i + 1
    add = '> 适配版说明：2026-10-08 依《艺术百家》投稿口径生成（镜像＋二手源·投稿前电话 025-84699052 复核）——字数 8000-15000✓；摘要 150-200 字✓；**英文题名/摘要约 80 words 需补**（见下）；体例改**页下脚注①②③＋文末 GB/T 7714 参考文献表**（现尾注制转换在 docx 生成器变体执行·[1]-[5] 表已具）；匿名审稿待复核（本稿即匿名形态）。差异清单见同夹 [投稿要求-2026-10-08.md](投稿要求-2026-10-08.md)。'
    lines.insert(ins_i, add)
    t = '\n'.join(lines)
    m = re.search(r'(把古典文学做成数据可视化[^\n]*\n)', t)
    if not m:
        fails.append('艺术百家版 中文摘要锚点缺失')
        return
    short = ('\n**Abstract**: Based on 86 interactive visualizations of *Journey to the West*, this article proposes a replicable "New Chinese Style" design system: '
             'motif-derived hues encoded as design tokens, motion constrained to tiered durations, accessibility built in, and a single-source pipeline ensuring replicability—'
             'indicating that indigenous aesthetics can become a transferable design methodology.\n')
    t = t.replace(m.group(1), m.group(1) + short, 1)
    out = os.path.join(ROOT, '05-投稿', '艺术百家投稿', '设计方向-艺术百家适配版（匿名）.md')
    open(out, 'w', encoding='utf-8', newline='').write(t)
    print('written', os.path.basename(out), len(t), 'chars')

make_ysbj()

print()
print('FAILS:', fails if fails else '无')
